---
- name: Check if server ready
  stat:
    path: /opt/ready.txt
  register: ready
- fail:
    msg: "Server is not ready!!!"
  when: not ready.stat.exists

- name: Configure floating IPs
  template:
    src: 60-floating-ip.j2
    dest: /etc/network/interfaces.d/60-floating-ip.cfg

- name: Restart Networking
  shell: systemctl restart networking.service

- name: Create temp folder for gobetween LB
  file:
    path: /tmp/gobetween
    state: directory

- name: Download and exract gobetween LB
  unarchive:
    src: https://github.com/yyyar/gobetween/releases/download/0.7.0/gobetween_0.7.0_linux_amd64.tar.gz
    dest: /tmp/gobetween
    remote_src: yes

- name: Copy gobeteen LB to path
  copy:
    src: /tmp/gobetween/gobetween
    dest: /usr/local/bin/gobetween
    remote_src: yes
    mode: u=rwx,g=rx,o=rx

- name: Clean gobetween LB temp folder
  file:
    state: absent
    path: /tmp/gobetween

- name: Create gobetween service config
  template:
    src: gobetween.service.j2
    dest: /etc/systemd/system/gobetween.service

- name: Create gobetween config
  template:
    src: gobetween.json.j2
    dest: /etc/gobetween.json

- name: Reload system daemon
  shell: systemctl daemon-reload
  
- name: Start gobetween service
  shell: systemctl start gobetween.service